services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "31500:27017" 
    volumes:
      - mongodb_data:/data/db 
    environment:
      MONGO_INITDB_ROOT_USERNAME:  
      MONGO_INITDB_ROOT_PASSWORD: 

volumes:
  mongodb_data:
    driver: local